version: '3.9'

services:
  habitus_achievements_ms:
    container_name: habitus_achievements_ms
    image: habitus_achievements_ms
    build: .
    ports:
      - 8181:8181
    environment:
      - DATABASE_URL=jdbc:postgresql://achievdb2-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - achievdb2-db
  # achievdb2-db:
  #   container_name: achievdb2-db
  #   image: postgres:12
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
